# Generated by Django 5.1.7 on 2025-03-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام دسته\u200cبندی"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="ExpertReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_text", models.TextField(verbose_name="متن بررسی")),
                (
                    "reviewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ بررسی"),
                ),
                ("score", models.IntegerField(default=0, verbose_name="امتیاز (0-10)")),
            ],
            options={
                "verbose_name": "بررسی کارشناس",
                "verbose_name_plural": "بررسی\u200cهای کارشناسان",
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting_date", models.DateTimeField(verbose_name="تاریخ جلسه")),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت\u200cها")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "جلسه",
                "verbose_name_plural": "جلسات",
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان درخواست"),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار"),
                            ("UNDER_REVIEW", "در حال بررسی"),
                            ("MEETING_SCHEDULED", "جلسه برنامه\u200cریزی شده"),
                            ("RESOLVED", "حل شده"),
                            ("REJECTED", "رد شده"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("LOW", "کم"), ("MEDIUM", "متوسط"), ("HIGH", "زیاد")],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="آخرین به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست",
                "verbose_name_plural": "درخواست\u200cها",
            },
        ),
        migrations.CreateModel(
            name="RequestHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_description", models.TextField(verbose_name="توضیحات تغییر")),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ تغییر"),
                ),
            ],
            options={
                "verbose_name": "تاریخچه درخواست",
                "verbose_name_plural": "تاریخچه درخواست\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Resolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resolution_text", models.TextField(verbose_name="متن تصمیم")),
                (
                    "resolved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ تصمیم"),
                ),
            ],
            options={
                "verbose_name": "تصمیم",
                "verbose_name_plural": "تصمیمات",
            },
        ),
    ]
