# Generated by Django 5.1.7 on 2025-03-13 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expertreview",
            name="expert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کارشناس",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="attendees",
            field=models.ManyToManyField(
                related_name="meetings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="حاضران",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="assigned_experts",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کارشناسان اختصاص داده شده",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="requests.category",
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests_submitted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ثبت\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="requests.request",
                verbose_name="درخواست",
            ),
        ),
        migrations.AddField(
            model_name="expertreview",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="requests.request",
                verbose_name="درخواست",
            ),
        ),
        migrations.AddField(
            model_name="requesthistory",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="تغییر دهنده",
            ),
        ),
        migrations.AddField(
            model_name="requesthistory",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="requests.request",
                verbose_name="درخواست",
            ),
        ),
        migrations.AddField(
            model_name="resolution",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolutions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تأیید کننده",
            ),
        ),
        migrations.AddField(
            model_name="resolution",
            name="request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resolution",
                to="requests.request",
                verbose_name="درخواست",
            ),
        ),
    ]
